### ISSUE TITLE
Should run with tini as pid 1 to avoid zombie npmlazy 

### ISSUE THREAD

**Issue by jamshid** [langri-sha/npm_lazy#26]
Sorry I don't have a repro but I think my npmlazy container locks up in some scenarios like when the docker server runs out of memory and it tries to kill the container.

I think the problem is that npmlazy is running as pid 1 -- you should always use a init system or tini instead. E.g. see:

https://blog.ghaiklor.com/avoid-running-nodejs-as-pid-1-under-docker-images-when-running-them-on-mesosphere-kubernetes-or-b7bd505657f9

I'm working around this by using this Dockerfile:

mynpmlazy/Dockerfile
```
ARG NPMLAZY_VERSION
FROM langrisha/npm-lazy:${NPMLAZY_VERSION}
ENV TINI_VERSION v0.17.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "-v", "-e", "143", "--", "node", "index.js"]
```

And start my npmlazy container using something like this in my docker-compose.yml:
```
  # https://registry.hub.docker.com/u/langrisha/npm-lazy/
  # To use add: ENV npm_config_registry http://${DOCKER_BUILD_CACHE_HOST}:8181
  npmlazy:
    restart: always
    image: mynpmlazy
    build:
      context: mynpmlazy/.
      args:
        - NPMLAZY_VERSION=1.11.0
    mem_limit: 500m
    memswap_limit: 500m
    volumes:
      - /root/.npm_lazy
    command: --show-config --port=80 --external-url=http://${DOCKER_BUILD_CACHE_HOST}:8181
```
